import test from"node:test";import assert from"node:assert/strict";import{newProduction,migrateProduction,PRODUCTION_SCHEMA_VERSION}from"../src/types/production.js";
import{classifyVideoDevice}from"../src/media/deviceClassification.js";
test("creates stable versioned production references",()=>{const p=newProduction({productionName:"Game",sport:"Football"});assert.equal(p.schemaVersion,PRODUCTION_SCHEMA_VERSION);assert.equal(p.productionName,"Game");assert.equal(p.homeTeamId,null);assert.ok(p.productionId);});
test("rejects future schemas",()=>assert.throws(()=>migrateProduction({schemaVersion:999}),/newer/));
test("new productions include customizable VERO-native inputs",()=>{const p=newProduction({productionName:"Game"});assert.equal(p.inputConfiguration.inputs.length,4);assert.deepEqual(p.inputConfiguration.inputs.map(input=>input.type),["capture","video","browser","gfx"]);assert.equal(p.inputConfiguration.programInputId,null);});
test("capture inputs are local devices rather than URL sources",()=>{const capture=newProduction().inputConfiguration.inputs[0];assert.equal(capture.type,"capture");assert.equal(capture.source,"");assert.equal(capture.audioSource,"");});
test("separates webcams from professional capture hardware",()=>{assert.equal(classifyVideoDevice("Integrated Webcam"),"webcam");assert.equal(classifyVideoDevice("Logitech BRIO"),"webcam");assert.equal(classifyVideoDevice("Blackmagic DeckLink Duo 2"),"capture");assert.equal(classifyVideoDevice("Elgato Cam Link 4K"),"capture");assert.equal(classifyVideoDevice("Magewell USB Capture HDMI"),"capture");});
test("migrates legacy productions to native inputs",()=>{const p=migrateProduction({schemaVersion:1,productionName:"Legacy",inputConfiguration:{}});assert.equal(p.schemaVersion,PRODUCTION_SCHEMA_VERSION);assert.equal(p.inputConfiguration.inputs.length,4);assert.equal(p.inputConfiguration.previewInputId,null);});
test("migrates old camera inputs to capture devices",()=>{const p=migrateProduction({schemaVersion:2,productionName:"Legacy",inputConfiguration:{inputs:[{id:"1",name:"Camera 1",type:"camera",source:"device"}]}});assert.equal(p.inputConfiguration.inputs[0].type,"capture");assert.equal(p.inputConfiguration.inputs[0].name,"Capture 1");});
