import { useMemo, useState } from "react";

function Monitor({label,input,tone}){return <section className={`monitor ${tone}`}><header><span>{label}</span><b>{input?input.label:"NO SIGNAL"}</b></header><div>{input?.thumbnail?<img src={input.thumbnail} alt=""/>:<><i>◫</i><strong>{input?.name||"No source selected"}</strong><small>{input?.type||"Configure a VERO input to begin."}</small></>}</div></section>}

export default function ProductionWorkspace({production,controller}){
  const native=useMemo(()=>(production.inputConfiguration?.inputs||[]).map((input,index)=>({...input,source:"vero",number:index+1,label:`VERO ${index+1}`})),[production.inputConfiguration]);
  const external=controller.vmix.status==="Connected"?(controller.vmix.state?.inputs||[]).map(input=>({...input,source:"vmix",id:`vmix-${input.key||input.number}`,label:`VMIX ${input.number}`})):[];
  const inputs=[...native,...external];
  const [nativePreview,setNativePreview]=useState(null),[nativeProgram,setNativeProgram]=useState(null);
  const vmixState=controller.vmix.state;
  const preview=native.find(input=>input.id===nativePreview)||external.find(input=>input.number===vmixState?.preview);
  const program=native.find(input=>input.id===nativeProgram)||external.find(input=>input.number===vmixState?.active);
  const select=input=>{if(input.source==="vmix"){setNativePreview(null);controller.selectPreview(input.number);}else setNativePreview(input.id);};
  const cut=()=>{if(preview?.source==="vmix"){setNativeProgram(null);controller.cut();}else{setNativeProgram(nativePreview);setNativePreview(null);}};
  const auto=()=>{if(preview?.source==="vmix"){setNativeProgram(null);controller.auto(production.transitionConfiguration.durationMs);}else{setNativeProgram(nativePreview);setNativePreview(null);}};
  return <div className="production-workspace"><section className="production-strip"><div><p>ACTIVE PRODUCTION</p><strong>{production.eventName||production.productionName}</strong><small>{[production.sport,production.date,production.venue].filter(Boolean).join(" · ")||"Local production"}</small></div><span className="offline">{vmixState?.streaming?"LIVE":vmixState?.recording?"RECORDING":"OFF AIR"}</span></section>{controller.settings.vmix.enabled&&controller.vmix.status!=="Connected"&&<div className="connection-warning">⚠ <span><strong>Optional vMix integration is disconnected</strong><small>{controller.vmix.error||"VERO Studio remains available with native inputs."}</small></span><button onClick={controller.refresh}>RETRY</button></div>}<div className="monitors"><Monitor label="PREVIEW" input={preview} tone="preview"/><Monitor label="PROGRAM" input={program} tone="program"/></div><section className="transition"><div><p>TRANSITION</p><strong>{production.transitionConfiguration.type} · {production.transitionConfiguration.durationMs} MS</strong></div><button disabled={!preview||controller.busy} onClick={cut}>CUT</button><button className="auto" disabled={!preview||controller.busy} onClick={auto}>AUTO</button></section><section className="input-section"><header><div><p>INPUTS</p><h2>Source selection</h2></div><small>VERO sources{external.length?" + connected vMix sources":""}</small></header><div className="input-grid">{inputs.length?inputs.map(input=><button key={`${input.source}-${input.id||input.key||input.number}`} className={`${input===preview?"is-preview":""} ${input===program?"is-program":""}`} onClick={()=>select(input)} disabled={controller.busy}><div>{input.thumbnail?<img src={input.thumbnail} alt=""/>:<span>{input.type?.slice(0,3).toUpperCase()||"IN"}</span>}{input===preview&&<b>PREVIEW</b>}{input===program&&<b>PROGRAM</b>}</div><strong>{input.name}</strong><small>{input.label} · {input.type}</small></button>):<div className="empty-grid"><strong>No VERO inputs configured</strong><small>Add sources from the Inputs page. vMix sources appear only when its optional integration is enabled and connected.</small></div>}</div></section></div>
}
