const destinations = [
  { id: "youtube", name: "YouTube" }, { id: "facebook", name: "Facebook" }, { id: "twitch", name: "Twitch" }, { id: "custom", name: "Custom RTMP / SRT" },
];
export default function StreamingPage({ production, onProductionChange }) {
  const config = production.streamingConfiguration || { destinations: {}, quality: "1080p60", bitrateKbps: 6000 };
  const update = (patch) => onProductionChange({ ...production, streamingConfiguration: { ...config, ...patch } });
  const updateDestination = (id, patch) => update({ destinations: { ...config.destinations, [id]: { ...(config.destinations?.[id] || {}), ...patch } } });
  return <section className="panel-page streaming-page"><header><div><p>DISTRIBUTION</p><h2>Streaming</h2></div><span>ENGINE PREVIEW</span></header><div className="stream-layout"><article><h3>Output profile</h3><div className="form-grid"><label>QUALITY<select value={config.quality} onChange={(event) => update({ quality: event.target.value })}><option>1080p60</option><option>1080p30</option><option>720p60</option><option>720p30</option></select></label><label>VIDEO BITRATE (KBPS)<input type="number" min="1000" max="20000" value={config.bitrateKbps} onChange={(event) => update({ bitrateKbps: Number(event.target.value) })} /></label></div><p>Studio will encode Program output once the native output engine is connected. These production-specific settings are preserved now.</p></article><article><h3>Destinations</h3><div className="destination-list">{destinations.map((destination) => { const state = config.destinations?.[destination.id] || {}; return <section key={destination.id}><label className="destination-toggle"><input type="checkbox" checked={Boolean(state.enabled)} onChange={(event) => updateDestination(destination.id, { enabled: event.target.checked })} /><span><strong>{destination.name}</strong><small>{destination.id === "custom" ? "RTMP and SRT endpoint" : "Platform connection"}</small></span></label>{state.enabled && <input value={state.label || ""} placeholder={destination.id === "custom" ? "Endpoint label (credentials later)" : "Account label (authorization later)"} onChange={(event) => updateDestination(destination.id, { label: event.target.value })} />}</section>; })}</div></article></div><div className="stream-action"><div><strong>Streaming engine coming in a later build</strong><small>Studio owns switching, encoding, and distribution. No credentials are transmitted by this preview.</small></div><button disabled>START STREAM</button></div></section>;
}
