export const PRODUCTION_SCHEMA_VERSION = 4;
const id=()=>crypto.randomUUID();
const transform=()=>({x:0,y:0,scale:100,rotation:0});
const colorCorrection=()=>({brightness:100,contrast:100,saturation:100,temperature:0,tint:0});
export const withInputDefaults=input=>({...input,transform:{...transform(),...(input.transform||{})},colorCorrection:{...colorCorrection(),...(input.colorCorrection||{})}});
export const defaultInputs=()=>[
  {id:id(),name:"Capture 1",type:"capture",source:"",audioSource:"",color:"#102832",audio:{enabled:false,muted:false,volume:100}},
  {id:id(),name:"Media 1",type:"video",source:"",color:"#14202a",audio:{enabled:true,muted:false,volume:100}},
  {id:id(),name:"Browser 1",type:"browser",source:"",color:"#17232d",audio:{enabled:false,muted:true,volume:100}},
  {id:id(),name:"VERO GFX",type:"gfx",source:"http://127.0.0.1:43111",color:"#063743",audio:{enabled:false,muted:true,volume:100}},
].map(withInputDefaults);
export function newProduction(input = {}) { const now=new Date().toISOString(); return { schemaVersion:PRODUCTION_SCHEMA_VERSION,productionId:id(),productionName:input.productionName?.trim()||"Untitled Production",workspaceId:null,accountId:null,eventId:null,eventName:input.eventName?.trim()||"",sport:input.sport?.trim()||"",homeTeamId:null,awayTeamId:null,date:input.date||now.slice(0,10),venue:input.venue?.trim()||"",graphicsPackageId:null,inputConfiguration:{inputs:defaultInputs(),previewInputId:null,programInputId:null},transitionConfiguration:{type:"Fade",durationMs:500},audioConfiguration:{master:{muted:false,volume:100}},streamingConfiguration:{quality:"1080p60",bitrateKbps:6000,destinations:{}},connections:{gfx:null,replay:null,audio:null},settings:{interfaceMode:"simple"},createdAt:now,updatedAt:now}; }
export function migrateProduction(value){if(!value||typeof value!=="object")throw new Error("Production file is invalid.");const version=value.schemaVersion||1;if(version>PRODUCTION_SCHEMA_VERSION)throw new Error("This production was created by a newer VERO Studio version.");const migrated={...newProduction({productionName:value.productionName}),...value,schemaVersion:PRODUCTION_SCHEMA_VERSION};if(version<2)migrated.inputConfiguration={inputs:value.inputConfiguration?.inputs?.length?value.inputConfiguration.inputs:defaultInputs(),previewInputId:null,programInputId:null};if(version<3)migrated.inputConfiguration={...migrated.inputConfiguration,inputs:(migrated.inputConfiguration?.inputs||[]).map(input=>input.type==="camera"?{...input,type:"capture",name:input.name==="Camera 1"?"Capture 1":input.name}:input)};migrated.inputConfiguration={...migrated.inputConfiguration,inputs:(migrated.inputConfiguration?.inputs||[]).map(withInputDefaults)};migrated.streamingConfiguration={quality:"1080p60",bitrateKbps:6000,destinations:{},...(migrated.streamingConfiguration||{})};migrated.settings={interfaceMode:"simple",...(migrated.settings||{})};return migrated;}
