export const SOURCE_CATALOG=[
  {type:"video",label:"Video",status:"available",description:"Local video file"},
  {type:"playlist",label:"List / Playlist",status:"planned",description:"Sequenced media playback"},
  {type:"capture",label:"Capture Device",status:"available",description:"HDMI / SDI / capture card"},
  {type:"webcam",label:"Webcam",status:"available",description:"Integrated or USB webcam"},
  {type:"desktop",label:"Desktop Capture",status:"planned",description:"Screen or application window"},
  {type:"ndi",label:"NDI / OMT",status:"planned",description:"Network video ingest"},
  {type:"stream",label:"Stream / SRT",status:"planned",description:"SRT, RTMP, and network streams"},
  {type:"replay",label:"Instant Replay",status:"planned",description:"VERO Replay source"},
  {type:"stinger",label:"Image Sequence / Stinger",status:"planned",description:"Animated transition source"},
  {type:"delay",label:"Video Delay",status:"planned",description:"Buffered live source"},
  {type:"image",label:"Image",status:"available",description:"Local still image"},
  {type:"photos",label:"Photos",status:"planned",description:"Photo slideshow"},
  {type:"powerpoint",label:"PowerPoint",status:"planned",description:"Presentation capture"},
  {type:"color",label:"Color",status:"available",description:"Solid background source"},
  {type:"audio",label:"Audio File",status:"planned",description:"Local audio media"},
  {type:"audio-input",label:"Audio Input",status:"planned",description:"Dedicated device channel"},
  {type:"title",label:"Title",status:"planned",description:"Native title composition"},
  {type:"virtual-set",label:"Virtual Set",status:"planned",description:"Layered set composition"},
  {type:"gfx",label:"VERO GFX",status:"available",description:"VERO graphics source"},
  {type:"browser",label:"Web Browser",status:"available",description:"Web page or browser overlay"},
  {type:"video-call",label:"Video Call",status:"planned",description:"Remote guest source"},
];
export const AVAILABLE_SOURCE_TYPES=SOURCE_CATALOG.filter(source=>source.status==="available");
